[package]
name = "dustweb"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.2"
actix-web = "4"
chrono = "0.4.23"
dustlog = { path = "../dustlog" } 
dustcfg = { path = "../dustcfg" }
serde_json = "1.0.94"
serde = "1.0.156"
email_address = "0.2.4"
pwhash = "1.0.0"
